server:
  port: 6001

spring:
  application:
    name: cas-gateway
  session:
    store-type: none

# zuul配置
zuul:
  routes:
    euredaclient1:
      path: /test1/**
      serviceId: test-application1
    springdemo:
      path: /test2/**
      serviceId: test-application2

# eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
